// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2voM62ZYhedtJC3uCaah4zW32VmP2s8',
    appId: '1:272310255031:web:75374c545a36c6cb79bc32',
    messagingSenderId: '272310255031',
    projectId: 'for-her-626e9',
    authDomain: 'for-her-626e9.firebaseapp.com',
    storageBucket: 'for-her-626e9.appspot.com',
    measurementId: 'G-LHWJ4DQNQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBljMH0oN4uQ6LX286Om7E5F1MJdI6CmvU',
    appId: '1:272310255031:android:83403e56dbf09d2579bc32',
    messagingSenderId: '272310255031',
    projectId: 'for-her-626e9',
    storageBucket: 'for-her-626e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjDuL6HTt8zywASLEvLTLrq6V9VcVyuk',
    appId: '1:272310255031:ios:c60b33ec0dea2d2d79bc32',
    messagingSenderId: '272310255031',
    projectId: 'for-her-626e9',
    storageBucket: 'for-her-626e9.appspot.com',
    iosBundleId: 'com.example.forHer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjDuL6HTt8zywASLEvLTLrq6V9VcVyuk',
    appId: '1:272310255031:ios:c60b33ec0dea2d2d79bc32',
    messagingSenderId: '272310255031',
    projectId: 'for-her-626e9',
    storageBucket: 'for-her-626e9.appspot.com',
    iosBundleId: 'com.example.forHer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBy2voM62ZYhedtJC3uCaah4zW32VmP2s8',
    appId: '1:272310255031:web:e8acd2d9188363e179bc32',
    messagingSenderId: '272310255031',
    projectId: 'for-her-626e9',
    authDomain: 'for-her-626e9.firebaseapp.com',
    storageBucket: 'for-her-626e9.appspot.com',
    measurementId: 'G-F2BF74VYG1',
  );
}
